/**
 * Turns a report snapshot (already in its language) into the PowerPoint deck model: translated titles, columns and
 * sentences, ₪ and dates formatted for the reader. The numbers are the snapshot's, unchanged.
 */
import type { ResolvedBlock } from "@/application/facade";
import { TEMPLATES } from "@/domain/report";
import { productName } from "@/i18n/brand";
import type { T } from "@/i18n/t";
import type { Deck, DeckSlide, DeckTable } from "@/infra/export/pptx";
import { day, dayTime } from "../_components/format";
import { ils } from "../_components/money-header";

const MONEY_COL = /₪|Actual|Budget|Month to date|End of|at stake/;
const TONE_HEX = { good: "34D399", watch: "FBBF24", bad: "F87171" } as const;

function cell(t: T, v: number | string | null, money: boolean) {
  if (v === null) return "—";
  if (typeof v === "string") return /^\d{4}-\d{2}-\d{2}/.test(v) ? day(t, v.slice(0, 10)) : t(v);
  return money ? ils(v) : Number.isInteger(v) ? v.toLocaleString("en-US") : v.toFixed(1);
}

function table(
  t: T,
  columns: string[],
  rows: { label: string; sub?: string; values: (number | string | null)[]; tone?: "good" | "watch" | "bad" | null }[],
): DeckTable {
  return {
    columns: columns.map((c) => t(c)),
    rows: rows.map((r) => ({
      cells: [
        r.sub ? `${r.label} · ${r.sub}` : r.label,
        ...r.values.map((v, k) => cell(t, v, MONEY_COL.test(columns[k + 1] ?? ""))),
      ],
      tone: r.tone ?? null,
    })),
  };
}

export function deckOf(
  t: T,
  r: {
    template: string;
    version: number;
    by: string;
    asOf: Date;
    contentHash: string;
    language: string;
    content: { asOf: string; scope: { name: string }; blocks: ResolvedBlock[] };
  },
): Deck {
  const templateTitle = t(TEMPLATES[r.template as keyof typeof TEMPLATES]?.title ?? r.template);
  const slides: DeckSlide[] = r.content.blocks.map((b): DeckSlide => {
    const title = t(b.title);
    const note =
      [b.scopeUnitId ? b.scopeName : null, b.data.type === "series" ? b.data.line : null].filter(Boolean).join(" · ") ||
      undefined;
    const d = b.data;
    switch (d.type) {
      case "headline":
        return {
          kind: "bullets",
          title,
          note,
          big:
            b.metric === "headline"
              ? {
                  value: String(d.health),
                  label: t("health"),
                  color: d.status === "healthy" ? TONE_HEX.good : d.status === "watch" ? TONE_HEX.watch : TONE_HEX.bad,
                }
              : undefined,
          bullets: d.sentences.map((s) =>
            t(
              s.text,
              Object.fromEntries(Object.entries(s.params ?? {}).map(([k, v]) => [k, k === "ils" ? ils(Number(v)) : v])),
            ),
          ),
        };
      case "series":
        return {
          kind: b.kind === "bars" ? "bar" : "line",
          title,
          note,
          categories: d.points.map((p) => p.label),
          series: [
            { name: t("actual"), values: d.points.map((p) => p.actual) },
            { name: t("budget"), values: d.points.map((p) => p.budget) },
          ],
          format: "ils",
        };
      case "bars":
        return {
          kind: "hbar",
          title,
          note,
          categories: d.rows.map((x) => x.label),
          series: [{ name: title, values: d.rows.map((x) => x.value) }],
          format: d.unit === "pct" ? "pct" : "num",
          colors: [d.rows.every((x) => x.tone === "good") ? TONE_HEX.good : "22D3EE"],
        };
      case "waterfall":
        return {
          kind: "bar",
          title,
          note,
          categories: [...d.steps.map((s) => s.label), t(d.end.label)],
          series: [{ name: title, values: [...d.steps.map((s) => s.value), d.end.value] }],
          format: "ils",
        };
      case "ring":
        return {
          kind: "doughnut",
          title,
          note,
          value: d.value,
          total: d.total,
          label: t(d.label),
          table: table(t, d.columns, d.rows),
        };
      case "table":
        return d.rows.length
          ? { kind: "table", title, note, table: table(t, d.columns, d.rows) }
          : { kind: "bullets", title, note, bullets: [t(d.empty ?? "Nothing to show.")] };
      default:
        return { kind: "bullets", title, note, bullets: [t(d.reason)] };
    }
  });
  return {
    rtl: r.language === "he",
    title: t("{template} report", { template: templateTitle }),
    subtitle: r.content.scope.name,
    meta: t("As of {date} · version {n} · generated by {name} on {when}", {
      date: day(t, r.content.asOf),
      n: r.version,
      name: r.by,
      when: dayTime(t, new Date(r.asOf)),
    }),
    footer: `${productName(r.language === "he" ? "he" : "en")} · ${r.content.scope.name} · sha256 ${r.contentHash.slice(0, 12)}`,
    slides,
  };
}
