/**
 * Plan v2, E5a (reports.md §1–§4): Dana edits the weekly management template (changes a chart, removes one, adds
 * one), generates it, and opens the snapshot; Noa can only report on Supply Chain; the Hebrew snapshot reads right to
 * left. Generates reports (new rows), which nothing else reads.
 */
import { expect, type Page, test } from "@playwright/test";

test.describe.configure({ mode: "serial" });
test.use({ viewport: { width: 1440, height: 900 } });

async function as(page: Page, name: string) {
  await page.goto("/login");
  await page
    .getByRole("button", { name: new RegExp(name) })
    .first()
    .click();
  await page.waitForURL((u) => !u.pathname.startsWith("/login"));
}

test("Dana edits the weekly management report and generates a snapshot", async ({ page }) => {
  await as(page, "Dana Levi");
  await page.getByRole("link", { name: "Reports", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1, name: "Reports builder" })).toBeVisible();
  const blocks = page.getByTestId("report-block");
  const n = await blocks.count();
  expect(n).toBeGreaterThan(8);
  // Edit: Sales vs budget as bars over 13 weeks.
  await page.getByTestId("report-section").filter({ hasText: "Sales vs budget" }).getByRole("link").first().click();
  const editor = page.getByTestId("block-editor");
  await editor.getByRole("link", { name: "bars", exact: true }).click();
  await editor.getByRole("link", { name: "last 13 weeks" }).click();
  await expect(page.locator('[data-metric="sales_vs_budget"]')).toContainText("last 13 weeks");
  // Remove the headcount chart, add costs vs budget.
  await page.getByTestId("report-section").filter({ hasText: "Headcount cost" }).getByTestId("remove-block").click();
  await expect(page.locator('[data-metric="headcount_cost"]')).toHaveCount(0);
  await page
    .getByTestId("add-chart")
    .getByRole("link", { name: /Costs vs budget/ })
    .click();
  await expect(page.locator('[data-metric="opex_vs_budget"]')).toBeVisible();
  await page.getByTestId("generate-report").click();
  await page.waitForURL(/\/reports\/[0-9a-f-]{36}$/);
  const snap = page.getByTestId("report-snapshot");
  await expect(snap.getByRole("heading", { level: 1 })).toContainText("Weekly management report · VECTOR Retail Group");
  await expect(snap.getByText(/version \d+ · generated by Dana Levi/)).toBeVisible();
  await expect(snap.locator('[data-metric="opex_vs_budget"]')).toBeVisible();
  await expect(snap.locator('[data-metric="headcount_cost"]')).toHaveCount(0);
  await page.goto("/reports");
  await expect(page.getByTestId("report-list").getByRole("link").first()).toContainText("VECTOR Retail Group");
});

test("Noa reports on Supply Chain only; the group report is not found for her", async ({ page }) => {
  await as(page, "Dana Levi");
  await page.goto("/reports");
  const href = await page.getByTestId("report-list").getByRole("link").first().getAttribute("href");
  await as(page, "Noa Friedman");
  await page.goto("/reports");
  await expect(page.locator("#report-scope option")).toHaveText(["Supply Chain"]);
  await page.getByTestId("generate-report").click();
  await page.waitForURL(/\/reports\/[0-9a-f-]{36}$/);
  await expect(page.getByTestId("report-snapshot").getByRole("heading", { level: 1 })).toContainText("Supply Chain");
  expect((await page.goto(href!))?.status()).toBe(404);
});

test("Hebrew: the snapshot is generated and read right to left", async ({ page, context }) => {
  await as(page, "Dana Levi");
  await context.addCookies([{ name: "vector_lang", value: "he", url: page.url() }]);
  await page.goto("/reports");
  await page.getByTestId("generate-report").click();
  await page.waitForURL(/\/reports\/[0-9a-f-]{36}$/);
  const snap = page.getByTestId("report-snapshot");
  await expect(snap).toHaveAttribute("dir", "rtl");
  await expect(snap.getByRole("heading", { level: 1 })).toContainText("דוח ניהולי שבועי");
});

test("E5b: the board pack template, and the snapshot as an editable PowerPoint", async ({ page }) => {
  await as(page, "Dana Levi");
  await page.goto("/reports");
  await page.locator("#report-template").selectOption("board_pack");
  await page.getByRole("button", { name: "Apply" }).click();
  await expect(page.locator('[data-metric="top_risks_opportunities"]')).toBeVisible();
  await expect(page.locator('[data-metric="health_by_region"]')).toBeVisible();
  await page.getByTestId("generate-report").click();
  await page.waitForURL(/\/reports\/[0-9a-f-]{36}$/);
  await expect(page.getByTestId("report-snapshot").getByRole("heading", { level: 1 })).toContainText(
    "Board pack report",
  );
  const [download] = await Promise.all([page.waitForEvent("download"), page.getByTestId("download-pptx").click()]);
  expect(download.suggestedFilename()).toMatch(/^vector-board-pack-v\d+-en\.pptx$/);
  const res = await page.request.get(page.url() + "/pptx");
  expect(res.headers()["content-type"]).toContain("presentationml");
  expect((await res.body()).subarray(0, 2).toString()).toBe("PK");
});
