import Link from "next/link";
import { api } from "@/app/_lib/api";
import {
  addBlock,
  editBlock,
  METRIC_IDS,
  METRICS,
  moveBlock,
  PERIODS,
  removeBlock,
  TEMPLATES,
  type Layout,
} from "@/domain/report";
import { generateReportAction } from "../../actions";
import { day, dayTime } from "../../_components/format";
import { BlockBody } from "../../_components/report-blocks";
import { Card, Notice, SectionTitle } from "../../_components/ui";
import { decodeLayout, encodeLayout } from "../../_lib/report-layout";
import { getT } from "../../_lib/locale";
import { requireActor } from "../../_lib/session";

const KIND_WORD: Record<string, string> = {
  line: "line",
  bars: "bars",
  ring: "ring",
  waterfall: "waterfall",
  table: "table",
  text: "text",
};
const PERIOD_WORD: Record<string, string> = { "4w": "last 4 weeks", "8w": "last 8 weeks", "13w": "last 13 weeks" };

/**
 * Reports builder (plan v2, E5; reports.md §2, wireframe v3 #6): start from a template, add, remove, reorder and edit
 * charts (type, period, scope), see the live preview, then generate an immutable snapshot. The layout lives in the URL,
 * so every edit is a link and the preview is always the server's numbers.
 */
export default async function ReportsPage({
  searchParams,
}: {
  searchParams: Promise<{ s?: string; l?: string; e?: string; error?: string }>;
}) {
  const sp = await searchParams;
  const { actor } = await requireActor();
  const t = await getT();
  const scopes = await api.reportScopes(actor);
  const list = await api.listReports(actor);
  if (scopes.length === 0)
    return (
      <>
        <h1 className="text-[26px] font-semibold tracking-tight">{t("Reports")}</h1>
        <p className="text-sm text-muted">{t("Reports are generated by the C-suite and department heads.")}</p>
      </>
    );
  const scope = scopes.find((x) => x.unitId === sp.s) ?? scopes[0];
  const isGroup = scope.kind === "group";
  const allowed = (id: string) => isGroup && scopes.some((x) => x.unitId === id && x.kind === "department");
  const layout = decodeLayout(sp.l, "weekly_management", allowed);
  const selected = layout.blocks.find((b) => b.id === sp.e) ?? null;
  const resolved = (await api.resolveReport(actor, scope.unitId, layout))!;
  const href = (l: Layout, e?: string | null) => `/reports?s=${scope.unitId}&l=${encodeLayout(l)}${e ? `&e=${e}` : ""}`;
  const title = t(TEMPLATES[layout.template].title);

  return (
    <>
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div className="flex flex-col gap-1">
          <h1 className="text-[26px] font-semibold tracking-tight">{t("Reports builder")}</h1>
          <p className="text-sm text-accent" data-testid="report-subtitle">
            {t("{template} report · {scope} · as of {date}", {
              template: title,
              scope: scope.name,
              date: day(t, resolved.asOf),
            })}
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <form className="flex items-center gap-2" action="/reports">
            <label className="text-xs text-muted" htmlFor="report-scope">
              {t("Scope")}
            </label>
            <select
              id="report-scope"
              name="s"
              defaultValue={scope.unitId}
              className="rounded-lg border border-line bg-panel px-3 py-2 text-sm"
            >
              {scopes.map((x) => (
                <option key={x.unitId} value={x.unitId}>
                  {x.name}
                </option>
              ))}
            </select>
            <input
              type="hidden"
              name="l"
              value={encodeLayout({ ...layout, blocks: layout.blocks.map((b) => ({ ...b, scopeUnitId: null })) })}
            />
            <button className="rounded-lg border border-line px-3 py-2 text-sm hover:border-accent">
              {t("Apply")}
            </button>
          </form>
          <form action={generateReportAction}>
            <input type="hidden" name="scope" value={scope.unitId} />
            <input type="hidden" name="layout" value={encodeLayout(layout)} />
            <button
              className="rounded-lg bg-accent px-5 py-2 font-semibold text-accent-ink"
              data-testid="generate-report"
            >
              {t("Generate")}
            </button>
          </form>
        </div>
      </div>
      <Notice error={sp.error} />
      <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,4fr)_minmax(0,9fr)]">
        <div className="flex min-w-0 flex-col gap-4">
          <Card className="flex flex-col gap-2" data-testid="report-sections">
            <SectionTitle aside={<span className="text-xs text-muted">{t("↑ ↓ to reorder · × to remove")}</span>}>
              {t("Sections")}
            </SectionTitle>
            <ol className="flex flex-col gap-1">
              {layout.blocks.map((b, k) => (
                <li
                  key={b.id}
                  className={`flex items-center gap-1 rounded-md px-2 py-1.5 text-sm ${selected?.id === b.id ? "bg-accent/15" : "bg-ground/60"}`}
                  data-testid="report-section"
                >
                  <Link
                    href={href(layout, b.id)}
                    className="min-w-0 grow truncate text-ink no-underline hover:underline"
                  >
                    {t(METRICS[b.metric].title)}
                    <span className="ms-2 text-xs text-muted">{t(KIND_WORD[b.kind])}</span>
                  </Link>
                  <Link
                    href={href(moveBlock(layout, b.id, -1), sp.e)}
                    aria-label={t("Move up")}
                    className={`rounded px-1.5 text-muted no-underline hover:text-ink ${k === 0 ? "pointer-events-none opacity-30" : ""}`}
                  >
                    ↑
                  </Link>
                  <Link
                    href={href(moveBlock(layout, b.id, 1), sp.e)}
                    aria-label={t("Move down")}
                    className={`rounded px-1.5 text-muted no-underline hover:text-ink ${k === layout.blocks.length - 1 ? "pointer-events-none opacity-30" : ""}`}
                  >
                    ↓
                  </Link>
                  <Link
                    href={href(removeBlock(layout, b.id), sp.e === b.id ? null : sp.e)}
                    aria-label={t("Remove")}
                    data-testid="remove-block"
                    className="rounded px-1.5 text-muted no-underline hover:text-p1"
                  >
                    ×
                  </Link>
                </li>
              ))}
            </ol>
          </Card>
          <Card className="flex flex-col gap-2" data-testid="add-chart">
            <SectionTitle>{t("Add a chart")}</SectionTitle>
            <div className="grid grid-cols-2 gap-2">
              {METRIC_IDS.map((m) => {
                const next = addBlock(layout, m);
                return (
                  <Link
                    key={m}
                    href={href(next, next.blocks.at(-1)!.id)}
                    className="rounded-md border border-line px-2 py-1.5 text-xs text-ink no-underline hover:border-accent/60"
                  >
                    + {t(METRICS[m].title)}
                    <span className="block text-muted">{METRICS[m].kinds.map((x) => t(KIND_WORD[x])).join(" · ")}</span>
                  </Link>
                );
              })}
            </div>
          </Card>
        </div>
        <Card className="flex min-w-0 flex-col gap-3" data-testid="report-canvas">
          <SectionTitle aside={<span className="text-xs text-muted">{t("click a chart's title to edit it")}</span>}>
            {t("Report canvas")}
          </SectionTitle>
          {selected && (
            <div
              className="flex flex-wrap items-center gap-2 rounded-lg border border-accent/40 bg-accent/5 px-3 py-2 text-xs"
              data-testid="block-editor"
            >
              <b className="text-sm">{t("Editing: {title}", { title: t(METRICS[selected.metric].title) })}</b>
              <span className="text-muted">{t("chart")}</span>
              {METRICS[selected.metric].kinds.map((k) => (
                <Link
                  key={k}
                  href={href(editBlock(layout, selected.id, { kind: k }), selected.id)}
                  aria-current={selected.kind === k ? "true" : undefined}
                  className={`rounded-md border px-2 py-0.5 no-underline ${selected.kind === k ? "border-accent text-accent" : "border-line text-ink"}`}
                >
                  {t(KIND_WORD[k])}
                </Link>
              ))}
              {METRICS[selected.metric].periods && (
                <>
                  <span className="ms-2 text-muted">{t("period")}</span>
                  {PERIODS.map((p) => (
                    <Link
                      key={p}
                      href={href(editBlock(layout, selected.id, { period: p }), selected.id)}
                      aria-current={selected.period === p ? "true" : undefined}
                      className={`rounded-md border px-2 py-0.5 no-underline ${selected.period === p ? "border-accent text-accent" : "border-line text-ink"}`}
                    >
                      {t(PERIOD_WORD[p])}
                    </Link>
                  ))}
                </>
              )}
              {isGroup && (
                <>
                  <span className="ms-2 text-muted">{t("scope")}</span>
                  {[
                    { unitId: null as string | null, name: scope.name },
                    ...scopes.filter((x) => x.kind === "department"),
                  ].map((x) => (
                    <Link
                      key={x.unitId ?? "all"}
                      href={href(editBlock(layout, selected.id, { scopeUnitId: x.unitId }), selected.id)}
                      aria-current={selected.scopeUnitId === x.unitId ? "true" : undefined}
                      className={`rounded-md border px-2 py-0.5 no-underline ${selected.scopeUnitId === x.unitId ? "border-accent text-accent" : "border-line text-ink"}`}
                    >
                      {x.name}
                    </Link>
                  ))}
                </>
              )}
              <Link href={href(layout)} className="ms-auto text-muted">
                {t("done")}
              </Link>
            </div>
          )}
          {layout.blocks.length === 0 && <p className="text-sm text-muted">{t("Add a chart to start.")}</p>}
          <div className="grid gap-3 lg:grid-cols-2">
            {resolved.blocks.map((b) => (
              <section
                key={b.id}
                data-testid="report-block"
                data-metric={b.metric}
                className={`min-w-0 rounded-lg border p-3 ${selected?.id === b.id ? "border-accent" : "border-line"} ${b.data.type === "table" || b.data.type === "ring" || b.metric === "headline" ? "lg:col-span-2" : ""}`}
              >
                <div className="mb-2 flex items-baseline justify-between gap-2">
                  <Link
                    href={href(layout, b.id)}
                    className="text-sm font-semibold text-ink no-underline hover:underline"
                  >
                    {t(b.title)}
                    {b.data.type === "series" && (
                      <span className="ms-2 text-xs font-normal text-muted">{b.data.line}</span>
                    )}
                  </Link>
                  <span className="text-xs text-muted">
                    {b.scopeUnitId ? b.scopeName : ""}
                    {b.period ? ` ${t(PERIOD_WORD[b.period])}` : ""}
                  </span>
                </div>
                <BlockBody b={b} t={t} />
              </section>
            ))}
          </div>
        </Card>
      </div>
      <Card className="flex flex-col gap-2" data-testid="report-list">
        <SectionTitle
          aside={<span className="text-xs text-muted">{t("each one is a snapshot that never changes")}</span>}
        >
          {t("Generated reports · {n}", { n: list.length })}
        </SectionTitle>
        {list.length === 0 ? (
          <p className="text-sm text-muted">{t("No report generated yet.")}</p>
        ) : (
          <table className="w-full text-sm">
            <tbody>
              {list.slice(0, 15).map((r) => (
                <tr key={r.id} className="border-t border-line">
                  <td className="py-1.5 pe-3">
                    <Link href={`/reports/${r.id}`} className="font-semibold text-ink no-underline hover:underline">
                      {t(TEMPLATES[r.template as keyof typeof TEMPLATES]?.title ?? r.template)} · {r.scopeName}
                    </Link>
                  </td>
                  <td className="whitespace-nowrap py-1.5 pe-3 text-xs text-muted">
                    {t("version {n}", { n: r.version })} · {r.language === "he" ? "עברית" : "English"}
                  </td>
                  <td className="whitespace-nowrap py-1.5 pe-3 text-xs text-muted">{dayTime(t, r.asOf)}</td>
                  <td className="py-1.5 text-xs text-muted">{r.by}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </Card>
    </>
  );
}
