import { notFound } from "next/navigation";
import { api as facade } from "@/application/facade";
import { TEMPLATES } from "@/domain/report";
import { localize } from "@/i18n/content";
import { makeT } from "@/i18n/t";
import { BackLink, Card } from "../../../_components/ui";
import { day, dayTime } from "../../../_components/format";
import { PrintButton } from "../../../_components/print-button";
import { BlockBody } from "../../../_components/report-blocks";
import { requireActor } from "../../../_lib/session";

/**
 * A generated report (plan v2, E5; reports.md §3): the immutable snapshot, shown in the language it was generated in,
 * with a print view. Only people who may read its scope can open it; anyone else gets "not found".
 */
export default async function ReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (!/^[0-9a-f-]{36}$/i.test(id)) notFound();
  const { actor } = await requireActor();
  const r = await facade.getReport(actor, id);
  if (!r) notFound();
  const lang = r.language === "he" ? "he" : "en";
  const t = makeT(lang);
  const content = localize(r.content, lang);
  const title = t(TEMPLATES[r.template as keyof typeof TEMPLATES]?.title ?? r.template);
  return (
    <div dir={lang === "he" ? "rtl" : "ltr"} lang={lang} className="flex flex-col gap-4" data-testid="report-snapshot">
      <div className="print:hidden">
        <BackLink href="/reports">{t("Reports")}</BackLink>
      </div>
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div className="flex flex-col gap-1">
          <h1 className="text-[26px] font-semibold tracking-tight">
            {t("{template} report", { template: title })} · {content.scope.name}
          </h1>
          <p className="text-sm text-muted">
            {t("As of {date} · version {n} · generated by {name} on {when}", {
              date: day(t, content.asOf),
              n: r.version,
              name: localize(r.by, lang),
              when: dayTime(t, new Date(r.asOf)),
            })}
          </p>
          <p
            className="font-mono text-[11px] text-muted"
            title={t("Content fingerprint: it changes if a single number changes")}
          >
            sha256 {r.contentHash.slice(0, 16)}
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2 print:hidden">
          <a
            href={`/reports/${id}/pptx`}
            className="rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-accent-ink no-underline"
            data-testid="download-pptx"
          >
            {t("PowerPoint (editable)")}
          </a>
          <PrintButton label={t("Print or save as PDF")} />
        </div>
      </div>
      <div className="grid gap-3 lg:grid-cols-2 print:block">
        {content.blocks.map((b) => (
          <Card
            key={b.id}
            className={`min-w-0 break-inside-avoid print:mb-3 ${b.data.type === "table" || b.data.type === "ring" || b.metric === "headline" ? "lg:col-span-2" : ""}`}
            data-testid="report-block"
            data-metric={b.metric}
          >
            <div className="mb-2 flex items-baseline justify-between gap-2">
              <h2 className="text-sm font-semibold">
                {t(b.title)}
                {b.data.type === "series" && <span className="ms-2 text-xs font-normal text-muted">{b.data.line}</span>}
              </h2>
              <span className="text-xs text-muted">{b.scopeUnitId ? b.scopeName : ""}</span>
            </div>
            <BlockBody b={b} t={t} />
          </Card>
        ))}
      </div>
    </div>
  );
}
